### ISSUE TITLE
Error "from zope.interface import implements" on some install

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/Tor2web#293]
On some installation with GlobaLeaks and Tor2web together on Ubuntu 14.04 there is this error at startup time:
root@XXXXX:~# /etc/init.d/tor2web start
 * Enabling Tor2web Apparmor Sandboxing...                                                                                                                                         * Starting Tor2web tor2web...                                                                                                                                                     * Starting tor daemon...                                                                                                                                                  [ OK ] 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tor2web/t2w.py", line 34, in <module>
    from zope.interface import implements
ImportError: No module named interface
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tor2web/t2w.py", line 34, in <module>
    from zope.interface import implements
ImportError: No module named interface

This ticket is to detect the erroneous condition at installation and/or startup time and fix it automatically and/or prevent the error in the specific condition.

**Comment by fpietrosanti** [comment]
A quick 'n' dirty workaround is to uninstall python-zone.interface, tor2web and then re-install tor2web:

apt-get remove python-zope.interface tor2web

apt-get install tor2web

**Comment by fiyona** [comment]
hello am still getting the same error but the above solution is failing

**Comment by fiyona** [comment]
ok am now getting this error
Tor2web Startup Failure: TRANSLATION config.mode require config.onion configuration

**Comment by evilaliv3** [comment]
This issue has been solved in the up-to-date release that avoid to install zope packages via pip.
