### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by 0x9090** [globaleaks/Tor2web#303]
I'm following the install instructions provided here, https://github.com/globaleaks/Tor2web/wiki/Installation-Guide but the `install-tor2web.sh` but the install script fails with the following error. I am building this on a fully patched Debian Jessie machine.

```
running build_ext

building '_Cryptography_cffi_f3e4673fx399b1113' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/src

creating build/temp.linux-x86_64-2.7/src/cryptography

creating build/temp.linux-x86_64-2.7/src/cryptography/hazmat

creating build/temp.linux-x86_64-2.7/src/cryptography/hazmat/bindings

creating build/temp.linux-x86_64-2.7/src/cryptography/hazmat/bindings/__pycache__

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_f3e4673fx399b1113.c -o build/temp.linux-x86_64-2.7/src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_f3e4673fx399b1113.o

src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_f3e4673fx399b1113.c:1926:15: error: ‘SSLv2_method’ redeclared as different kind of symbol

 SSL_METHOD* (*SSLv2_method)(void) = NULL;

               ^

In file included from src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_f3e4673fx399b1113.c:265:0:

/usr/include/openssl/ssl.h:2021:19: note: previous declaration of ‘SSLv2_method’ was here

 const SSL_METHOD *SSLv2_method(void); /* SSLv2 */

                   ^

src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_f3e4673fx399b1113.c:1927:15: error: ‘SSLv2_client_method’ redeclared as different kind of symbol

 SSL_METHOD* (*SSLv2_client_method)(void) = NULL;

               ^

In file included from src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_f3e4673fx399b1113.c:265:0:

/usr/include/openssl/ssl.h:2023:19: note: previous declaration of ‘SSLv2_client_method’ was here

 const SSL_METHOD *SSLv2_client_method(void); /* SSLv2 */

                   ^

src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_f3e4673fx399b1113.c:1928:15: error: ‘SSLv2_server_method’ redeclared as different kind of symbol

 SSL_METHOD* (*SSLv2_server_method)(void) = NULL;

               ^

In file included from src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_f3e4673fx399b1113.c:265:0:

/usr/include/openssl/ssl.h:2022:19: note: previous declaration of ‘SSLv2_server_method’ was here

 const SSL_METHOD *SSLv2_server_method(void); /* SSLv2 */

                   ^

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
  Can't roll back cryptography; was not uninstalled
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-9C5QzQ/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-hpArjX-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-9C5QzQ/cryptography
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 248, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 104: ordinal not in range(128)
dpkg: error processing package tor2web (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 tor2web
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by NSkelsey** [comment]
@0x9090 I can confirm this is reproducible issue. I ran into this on a jessie VM a few days ago. Thanks for reporting it.

This is an issue with `pip install cryptography` a [pyca package & issue](https://github.com/pyca/cryptography/issues/2973). It looks like Jessie might have a solution coming down the release path. . . ? https://github.com/lyft/confidant/issues/81

More research is needed.

**Comment by NSkelsey** [comment]
Herp derp, Debian will not fix, that's lyft issue.

We could simply bump the version of the cryptography package until the issue magically disappears.

**Comment by evilaliv3** [comment]
Tor2web is currently using one only requirement.txt that is the same for every distribution.

What we have to do is to do the same done for globaleaks in using a different requirements.txt file following: https://github.com/globaleaks/Tor2web/issues/266

this will be probably done in the next months but in general the only distribution taken into consideration for official support will be Ubuntu in all its LTS versions.
