### ISSUE TITLE
MAC OSX 10.11.6 error

### ISSUE THREAD

**Issue by hktalent** [globaleaks/Tor2web#306]
Running setup.py install for enum34 ... done
  Running setup.py install for cryptography ... error
    Complete output from command /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;**file**='/private/tmp/pip-build-O38dKC/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-yi9VNW-record/install-record.txt --single-version-externally-managed --compile:
    running install
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-O38dKC/cryptography/setup.py", line 342, in <module>
        **keywords_with_side_effects(sys.argv)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 971, in run_command
        cmd_obj.ensure_finalized()
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "/private/tmp/pip-build-O38dKC/cryptography/setup.py", line 119, in finalize_options
        self.distribution.ext_modules = get_ext_modules()
      File "/private/tmp/pip-build-O38dKC/cryptography/setup.py", line 78, in get_ext_modules
        from cryptography.hazmat.bindings.commoncrypto.binding import (
      File "/private/tmp/pip-build-O38dKC/cryptography/src/cryptography/hazmat/bindings/commoncrypto/binding.py", line 14, in <module>
        class Binding(object):
      File "/private/tmp/pip-build-O38dKC/cryptography/src/cryptography/hazmat/bindings/commoncrypto/binding.py", line 36, in Binding
        "-framework", "Security", "-framework", "CoreFoundation"
      File "/private/tmp/pip-build-O38dKC/cryptography/src/cryptography/hazmat/bindings/utils.py", line 97, in build_ffi_for_binding
        extra_link_args=extra_link_args,
      File "/private/tmp/pip-build-O38dKC/cryptography/src/cryptography/hazmat/bindings/utils.py", line 105, in build_ffi
        ffi = FFI()
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cffi/api.py", line 59, in **init**
        "version mismatch, %s != %s" % (backend.**version**, **version**)
    AssertionError: version mismatch, 0.8.2 != 1.7.0

```
----------------------------------------
```

Command "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;**file**='/private/tmp/pip-build-O38dKC/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-yi9VNW-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-O38dKC/cryptography/
##

**Comment by evilaliv3** [comment]
Hi Neo!

Tor2web currently is supported only on Ubuntu and it is not expected to work on OSX.
If you would like to try to make it work there you should start working on the dependencies (mostrly on the requirements.txt) and be sure that all the requirements needed are present on your system.

I would suggest that you start using the development guide at https://github.com/globaleaks/Tor2web/wiki/Setting-up-development-environment and you setup a virtualenv
