### ISSUE TITLE
Unhandled error in Deferred.

### ISSUE THREAD

**Issue by cheako** [globaleaks/Tor2web#344]
I have no idea what this means, if someone could explain it to me that would be helpful.

Thanks.

https://travis-ci.org/cheako/Tor2web-1/builds/285157269#L1476

```
Unhandled error in Deferred:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 1655, in lineReceived
    self.allHeadersReceived()
  File "/usr/local/lib/python2.7/dist-packages/tor2web-3.1.70-py2.7.egg/tor2web/t2w.py", line 1145, in allHeadersReceived
    self.requests[-1].requestReceived(self._command, self._path, self._version)
  File "/usr/local/lib/python2.7/dist-packages/tor2web-3.1.70-py2.7.egg/tor2web/t2w.py", line 524, in requestReceived
    self.process()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/dist-packages/tor2web-3.1.70-py2.7.egg/tor2web/t2w.py", line 928, in process
    self.sendError(404)
  File "/usr/local/lib/python2.7/dist-packages/tor2web-3.1.70-py2.7.egg/tor2web/t2w.py", line 644, in sendError
    return flattenString(self, templates[errortemplate]).addCallback(self.writeContent)
exceptions.KeyError: 'error_generic.tpl'
```

**Comment by evilaliv3** [comment]
@cheako: tor2web uses some files .tpl in order to build the html pages shown for example during errors.

this semplates are indexed in a dictionaty via their name, and it seems that the dictionary is not containing all the keys;
maybe you do not have a directory 'templates' loaded on your system local to the tor2web instance? the files shuld be placed in /home/tor2web/templates

**Comment by cheako** [comment]
Thanks, I found the real path it's here:
https://github.com/globaleaks/Tor2web/blob/master/tor2web/t2w.py#L1514

Though the error should indicate "File not found" and the path that the file should be.

**Comment by cheako** [comment]
This can be closed, unless someone is going to change the errormsg to be more useful.
