### ISSUE TITLE
Tor2web Error: Generic Error (500)

### ISSUE THREAD

**Issue by eBug** [globaleaks/Tor2web#364]
Debian 10 - buster

tor2web 

```
Nov 22 12:08:59 VPS-2 Tor[4939]: Tried for 120 seconds to get a connection to [scrubbed]:80. Giving up. (waiting for rendezvous desc)
Nov 22 12:09:13 VPS-2 Tor[4939]: Tried for 120 seconds to get a connection to [scrubbed]:80. Giving up. (waiting for rendezvous desc)
Nov 22 12:10:28 VPS-2 tor2web[4907]: /usr/lib/python3/dist-packages/tor2web/t2w.py:721: DeprecationWarning: twisted.web.http.Request.getClientIP was deprecated in Twisted 18.4.0; please use getClientAddress instead
Nov 22 12:10:28 VPS-2 tor2web[4907]:   self.obj.client_ip = self.getClientIP()
Nov 22 12:10:28 VPS-2 tor2web[4907]: Unhandled Error
Nov 22 12:10:28 VPS-2 tor2web[4907]: Traceback (most recent call last):
Nov 22 12:10:28 VPS-2 tor2web[4907]:   File "/usr/lib/python3/dist-packages/tor2web/t2w.py", line 1461, in <module>
Nov 22 12:10:28 VPS-2 tor2web[4907]:     reactor.run()
Nov 22 12:10:28 VPS-2 tor2web[4907]:   File "/usr/lib/python3/dist-packages/twisted/internet/base.py", line 1267, in run
Nov 22 12:10:28 VPS-2 tor2web[4907]:     self.mainLoop()
Nov 22 12:10:28 VPS-2 tor2web[4907]:   File "/usr/lib/python3/dist-packages/twisted/internet/base.py", line 1276, in mainLoop
Nov 22 12:10:28 VPS-2 tor2web[4907]:     self.runUntilCurrent()
Nov 22 12:10:28 VPS-2 tor2web[4907]: --- <exception caught here> ---
Nov 22 12:10:28 VPS-2 tor2web[4907]:   File "/usr/lib/python3/dist-packages/twisted/internet/base.py", line 902, in runUntilCurrent
Nov 22 12:10:28 VPS-2 tor2web[4907]:     call.func(*call.args, **call.kw)
Nov 22 12:10:28 VPS-2 tor2web[4907]:   File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2333, in forceAbortClient
Nov 22 12:10:28 VPS-2 tor2web[4907]:     self.transport.abortConnection()
Nov 22 12:10:28 VPS-2 tor2web[4907]:   File "/usr/lib/python3/dist-packages/twisted/protocols/tls.py", line 435, in abortConnection
Nov 22 12:10:28 VPS-2 tor2web[4907]:     self._shutdownTLS()
Nov 22 12:10:28 VPS-2 tor2web[4907]:   File "/usr/lib/python3/dist-packages/twisted/protocols/tls.py", line 338, in _shutdownTLS
Nov 22 12:10:28 VPS-2 tor2web[4907]:     shutdownSuccess = self._tlsConnection.shutdown()
Nov 22 12:10:28 VPS-2 tor2web[4907]: builtins.AttributeError: 'NoneType' object has no attribute 'shutdown'
Nov 22 12:11:33 VPS-2 Tor[4939]: Tried for 120 seconds to get a connection to [scrubbed]:80. Giving up. (waiting for rendezvous desc)
```

**Comment by eBug** [comment]
i don't have more details
