### ISSUE TITLE
i need support "Unhandled error in Deferred"

### ISSUE THREAD

**Issue by yohohoro** [globaleaks/Tor2web#370]
strace -f -vvv -o strace-tor2web.out tor2web --pidfile /var/run/tor2web/t2w.pid --uid tor2web --gid tor2web --nodaemon --command=start
 2020-02-01 08:03:37+0000 ] Log opened.
 2020-02-01 08:03:37+0000 [ PBServerFactory starting on '/var/run/tor2web/rpc.socket'
 2020-02-01 08:03:37+0000 ] Starting factory 
 2020-02-01 08:03:37+0000 [ Starting factory _HTTP11ClientFactory(.quiescentCallback at 0x7efd458b4378>, )
 2020-02-01 08:03:37+0000 [-] Stopping factory _HTTP11ClientFactory(.quiescentCallback at 0x7efd458b4378>, )
 Unhandled error in Deferred:

 Traceback (most recent call last):
 File "/usr/lib/python3/dist-packages/tor2web/t2w.py", line 1040, in allHeadersReceived
 self.requests[-1].requestReceived(self._command, self._path, self._version)
 File "/usr/lib/python3/dist-packages/tor2web/t2w.py", line 469, in requestReceived
 self.process()
 File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
 return _cancellableInlineCallbacks(gen)
 File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
 _inlineCallbacks(None, g, status)
 ---  ---
 File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
 result = g.send(result)
 File "/usr/lib/python3/dist-packages/tor2web/t2w.py", line 712, in process
 self.redirect("https://" + request.host + request.uri)
 builtins.TypeError: can only concatenate str (not "bytes") to str

**Comment by yohohoro** [comment]
ls -la /home/tor2web/certs/
total 24
drwxrwx--- 2 tor2web tor2web 4096 Feb  1 07:21 .
drwxrwx--- 5 tor2web tor2web 4096 Feb  1 07:04 ..
-rw-r--r-- 1 tor2web tor2web 1818 Feb  1 07:21 tor2web-cert.pem
-rw-r--r-- 1 tor2web tor2web 1651 Feb  1 07:20 tor2web-csr.pem
-rw-r--r-- 1 tor2web tor2web  424 Feb  1 07:22 tor2web-dh.pem
-rw------- 1 tor2web tor2web 3243 Feb  1 07:16 tor2web-key.pem

**Comment by yohohoro** [comment]
debug.log
2020-02-01 08:20:14+0000 [twisted.spread.pb.PBServerFactory] (UNIX Port /var/run/tor2web/rpc.socket Closed)
2020-02-01 08:20:14+0000 [-] Stopping factory <twisted.spread.pb.PBServerFactory object at 0x7f23de4be278>
2020-02-01 08:20:14+0000 [-] Main loop terminated.
2020-02-01 08:44:17+0000 [-] Log opened.
2020-02-01 08:44:17+0000 [-] PBServerFactory starting on '/var/run/tor2web/rpc.socket'
2020-02-01 08:44:17+0000 [-] Starting factory <twisted.spread.pb.PBServerFactory object at 0x7f8d7f4952b0>
2020-02-01 08:44:17+0000 [-] Starting factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at 0x7f8d7f4f3378>, <twisted.internet.endpoints._WrapperEndpoint object at 0x7f8d80c53d30>)

**Comment by yohohoro** [comment]
netstat -natp | grep -e LISTEN | grep -e ':80' -e ':443'
tcp6       0      0 :::80                   :::*                    LISTEN      446/python3
tcp6       0      0 :::443                  :::*                    LISTEN      446/python3
